# .github/dependabot.yml
version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/"
      - "/.github/workflows/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: friday
      time: '04:00'

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: friday
      time: '04:10'

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: friday
      time: '04:20'
