apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
data:
  {{- with .Values.config }}
  CLEANUP: {{ .cleanup | default "false" | quote }}
  DRY_RUN: {{ .dryRun | default "false" | quote }}
  OS_AUTH_URL: {{ .osAuthUrl | quote }}
  OS_IDENTITY_API_VERSION: {{ .osIdentityApiVersion | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .osProjectDomainName | quote }}
  OS_PROJECT_ID: {{ .osProjectId | quote }}
  OS_REGION_NAME: {{ .osRegionName | quote }}
  OS_TENANT_ID: {{ .osTenantId | quote }}
  OS_TENANT_NAME: {{ .osTenantName | quote }}
  OS_USER_DOMAIN_NAME: {{ .osUserDomainName | quote }}
  OS_VOLUMES: {{ .osVolumes | join "," | quote }}
  {{- end }}
