apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
type: Opaque
data:
  OS_PASSWORD: {{ .Values.config.osPassword | default "password" | b64enc }}
  OS_USERNAME: {{ .Values.config.osUsername | default "user"     | b64enc }}
